namespace Euler.Console.Problems;

/* 
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with $1$ and $2$, the first $10$ terms will be:
$$1, 2, 3, 5, 8, 13, 21, 34, 55, 89, \dots$$
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fn(limit?) => Add(# when == (# % 2 !== 0))
*/

public class Problem002
{
    public static List<int> Fibber(int limit)
    {
        List<int> fibs = [1, 2];
        int pointerIdx = 1;
        int next = Next(fibs, pointerIdx);

        while (next <= limit)
        {
            pointerIdx++;
            fibs.Add(next);
            next = Next(fibs, pointerIdx);
        }

        return fibs;

        static int Next(List<int> fibs, int pointerIdx)
        {
            return fibs[pointerIdx] + fibs[pointerIdx - 1];
        }
    }

    public static int Sum_Even_Fibs(List<int> list)
    {
        return list.Where(n => n % 2 == 0).Sum();
    }
}